version: '3.1'

services:

  mongo:
    image: mongo:bionic
    restart: always
    ports:
      - 127.0.0.1:27017:27017/tcp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    volumes:
      - /var/local/mongo_db:/data/db

